- name: Pull docker image of the container from DockerHub
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Pull docker image from docker hub
      shell: docker pull lax98/scientific_calculator:latest

    - name: Run the docker container
      shell: docker stop scientific_calculator && docker rm scientific_calculator && docker run -it --name scientific_calculator -d lax98/scientific_calculator
